FROM alpine:3.6
MAINTAINER anan 
ENV SERVER_ADDR 0.0.0.0
ENV SERVER_PORT 2333
ENV PASSWORD javawebrumenjingdian
ENV METHOD aes-256-cfb
ENV PROTOCOL auth_aes128_sha1
ENV PROTOCOLPARAM 32
ENV OBFS tls1.2_ticket_fastauth
ENV TIMEOUT 300
ENV DNS_ADDR 8.8.8.8
ENV DNS_ADDR_2 8.8.4.4

ARG BRANCH=manyuser
ARG WORK=~


RUN apk --no-cache add python \
libsodium \
wget


RUN mkdir -p $WORK && \
wget -qO- --no-check-certificate https://github.com/shadowsocksr/shadowsocksr/archive/$BRANCH.tar.gz | tar -xzf - -C $WORK


WORKDIR $WORK/shadowsocksr-$BRANCH/shadowsocks


EXPOSE $SERVER_PORT
CMD python server.py -p $SERVER_PORT -k $PASSWORD -m $METHOD -O $PROTOCOL -o $OBFS -G $PROTOCOLPARAM